### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by Jameshuang8045** [mooseIre/update_miui_ota#2]
请问这些包也是得用系统更新解密安装吗？

**Comment by mooseIre** [comment]
Plan1:用第三方REC直接卡刷
Plan2:申请权限后官方系统更新选择安装包更新

**Comment by Jameshuang8045** [comment]
太好了谢谢你！我的刷最新内测包无限重启了 就想着这个可能可以卡刷




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "moose"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 上午9:01
收件人: "mooseIre/update_miui_ota"<update_miui_ota@noreply.github.com&gt;; 
抄送: "爿"<2535538045@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mooseIre/update_miui_ota] 作者你好 (#2)





 
Plan1:用第三方REC直接卡刷
 Plan2:申请权限后官方系统更新选择安装包更新

**Comment by Jameshuang8045** [comment]
刷好了，成功了再次回复还是很感激




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "moose"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 上午9:01
收件人: "mooseIre/update_miui_ota"<update_miui_ota@noreply.github.com&gt;; 
抄送: "爿"<2535538045@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mooseIre/update_miui_ota] 作者你好 (#2)





 
Plan1:用第三方REC直接卡刷
 Plan2:申请权限后官方系统更新选择安装包更新
