### ISSUE TITLE
???

### ISSUE THREAD

**Issue by A3148475824** [mooseIre/update_miui_ota#23]
笑死我了，没有账号啊，你下载了也没有用啊，我真是服了。有屌用啊，你下载完之后还得要账号，没有账号你怎么用？没有内测账号啊，难道你提供啊？

**Comment by mooseIre** [comment]
我有收集地址的爱好。对不起。

**Comment by maxwell-nc** [comment]
很好用，想刷回旧版很方便，谢谢

**Comment by A3148475824** [comment]
不过你真是牛逼你给我了一个思路完全可以吧Github变成一个网盘

**Comment by simo8102** [comment]
> 笑死我了，没有账号啊，你下载了也没有用啊，我真是服了。有屌用啊，你下载完之后还得要账号，没有账号你怎么用？没有内测账号啊，难道你提供啊？

你不知道有解bi和twrp这玩意嘛？你刷不了不代表别人不行 动动脑子在说话

**Comment by reallxuan** [comment]
> 笑死我了，没有账号啊，你下载了也没有用啊，我真是服了。有屌用啊，你下载完之后还得要账号，没有账号你怎么用？没有内测账号啊，难道你提供啊？

鱼上钩了，马没了，值得吗？？？？？？？？？
真是白费了有个脑子

**Comment by Kaneki521** [comment]
啊这？脑子是个好东西

**Comment by Kaneki521** [comment]
人家只是提供了链接而已 怎么用是自己的事 自己不行就骂人家 人家不欠你钱 没有义务给你刷完了让你用！下次说话记得过脑子

**Comment by A3148475824** [comment]
> 人家只是提供了链接而已 怎么用是自己的事 自己不行就骂人家 人家不欠你钱 没有义务给你刷完了让你用！下次说话记得过脑子

我骂了吗？搞笑自己理解非人类

**Comment by zhullyb** [comment]
> 不过你真是牛逼你给我了一个思路完全可以吧Github变成一个网盘

只不过是收集了MIUI的下载地址罢了，并不是用Github存包

**Comment by NO1bbt** [comment]
，，，，

**Comment by Cathgao** [comment]
> 不过你真是牛逼你给我了一个思路完全可以吧Github变成一个网盘

还网盘，笑死我了，有没有脑子这时候就体现出来了。连这仓库里面装的是什么都不知道就别出来秀了

**Comment by zhugexiaoshang** [comment]
https://miuiver.com/
