### ISSUE TITLE
夸版本升级

### ISSUE THREAD

**Issue by zhq111** [mooseIre/update_miui_ota#24]
大神，我现在红米10x PRO MIUI 12 20.11.5 开发版，怎么升级MIUI 12.5呀。我小白，希望大神帮忙.谢谢

**Comment by reallxuan** [comment]
解锁，刷twrp，直接刷！

**Comment by zhq111** [comment]
> 解锁，刷twrp，直接刷！

这样搞过，结果成砖，线刷才救回，数据全丢

**Comment by NO1bbt** [comment]
可以直接刷就行了

**Comment by mooseIre** [comment]
twrp直接刷
