### ISSUE TITLE
小米11Ultra 稳定版地址

### ISSUE THREAD

**Issue by dzshzx** [mooseIre/update_miui_ota#26]
V12.0.9.0

https://hugeota.d.miui.com/V12.0.9.0.RKACNXM/miui_STAR_V12.0.9.0.RKACNXM_be719560cb_11.0.zip

**Comment by NO1bbt** [comment]
谢谢

**Comment by dzshzx** [comment]
V12.0.10.0

https://hugeota.d.miui.com/V12.0.10.0.RKACNXM/miui_STAR_V12.0.10.0.RKACNXM_89b8a90dec_11.0.zip

**Comment by mooseIre** [comment]
thanks
