### ISSUE TITLE
老哥有没有安装教程

### ISSUE THREAD

**Issue by alex520** [mooseIre/update_miui_ota#27]
不要脸的求一下=-=

**Comment by djs326** [comment]
那你确实够不要脸的




K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mooseIre/update_miui_ota"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 晚上10:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mooseIre/update_miui_ota] 老哥有没有安装教程 (#27)





 
不要脸的求一下=-=

**Comment by zhangzihanxuejingjing** [comment]
说的没毛病，确实够不要脸的
