### ISSUE TITLE
博主，啥时候加一个redmik30pro的地址

### ISSUE THREAD

**Issue by liulei92** [mooseIre/update_miui_ota#3]

**Comment by mooseIre** [comment]
已经有了啊 :)

**Comment by liulei92** [comment]
我咋只看到 k30和k30 5g，没有 k30pro的。。

**Comment by mooseIre** [comment]
> 我咋只看到 k30和k30 5g，没有 k30pro的。。

https://github.com/mooseIre/update_miui_ota/blob/master/Develop/Redmi%20K30Pro.md

**Comment by liulei92** [comment]
好的，一直以来都是只看了 read.md的，没注意
