### ISSUE TITLE
Camera redmi note 7

### ISSUE THREAD

**Issue by Courtois7-cmd** [mooseIre/update_miui_ota#31]
hello, does the camera work redmi notes 7 3/32, otherwise it crashes and freezes on the assembly from xiaomi.eu?

**Comment by ingbrzy** [comment]
@Courtois7-cmd download xiaomi.eu ROM again.. it was already fixed..

**Comment by Courtois7-cmd** [comment]
> @Courtois7-cmd download xiaomi.eu ROM again.. it was already fixed..

But what is here then for the beta firmware? isn't it like xiaomi.eu?
