### ISSUE TITLE
建议能不能吧线刷包的地址也搞进去。我想降级

### ISSUE THREAD

**Issue by kabaom** [mooseIre/update_miui_ota#32]

**Comment by kabaom** [comment]
> 这本就是免费的分享，如果需要可以到小米社区对应的手机版块有对应的线刷包

目前只有最新的保留，而我想要的是历史版的

**Comment by LoveCany** [comment]
> > 这本就是免费的分享，如果需要可以到小米社区对应的手机版块有对应的线刷包
> 
> 目前只有最新的保留，而我想要的是历史版的

https://xiaomifirmwareupdater.com/
