### ISSUE TITLE
请求为刷机包文件也添加json格式的文件

### ISSUE THREAD

**Issue by chs72** [mooseIre/update_miui_ota#42]
如题

**Comment by zhangzihanxuejingjing** [comment]
这不太可能

**Comment by chs72** [comment]
> 这不太可能

哈哈，为啥你觉得不可能呢

**Comment by zhangzihanxuejingjing** [comment]
因为这些文件只是作者对miui官方的下载地址的简单上传，如果你懂的话，可以看一下后台。而且如果强行改变文件类型会导致文件无法打开等问题。如果你行的话，自己可以尝试，不要苛求一个免费给你提供服务的人。

**Comment by chs72** [comment]
> 因为这些文件只是作者对miui官方的下载地址的简单上传，如果你懂的话，可以看一下后台。而且如果强行改变文件类型会导致文件无法打开等问题。如果你行的话，自己可以尝试，不要苛求一个免费给你提供服务的人。

1. markdown和json你懂啥是吗？“强行改变文件类型”？
2.我没有要求作者怎么样，我只是提一个请求，新增文件格式，方便第三方开发人员更方便的调用json
3.我说的你可能都不懂，github不是你用来闲聊、diss的地方，是对项目、代码交流的地方，不是让你来发挥个人见解的。

**Comment by zhangzihanxuejingjing** [comment]
你牛的话，就不应该和我在这掰扯，早就自己做好了，而不是在这让上传者给你提供便利。会写代码是你自己专业知识给你带来的本领，而不是让你在这里叫嚣的资本。术业有专攻，别觉得自己有多牛。这是一个面向所有人的网站，不只是专为你而提供。我只是发表自己的见解，我不知你算什么东西。有本事就让我禁言，懂吗？键盘侠

**Comment by mooseIre** [comment]
现在小米内测权限回收了，没法抓取了。

**Comment by chs72** [comment]
> 你牛的话，就不应该和我在这掰扯，早就自己做好了，而不是在这让上传者给你提供便利。会写代码是你自己专业知识给你带来的本领，而不是让你在这里叫嚣的资本。术业有专攻，别觉得自己有多牛。这是一个面向所有人的网站，不只是专为你而提供。我只是发表自己的见解，我不知你算什么东西。有本事就让我禁言，懂吗？键盘侠

我错了，对不起，我又犯错了，不应该在网络中太认真，给你道歉，希望你不要再回复了，谢谢大哥。

**Comment by chs72** [comment]
> 现在小米内测权限回收了，没法抓取了。
> 

好多人都被收回了，理解。谢谢回复

**Comment by zhangzihanxuejingjing** [comment]
我本来也没针对你，是你自己说话阴阳怪气的，如果你在生活中也这么阴阳怪气的，我不多说。

**Comment by chs72** [comment]
> 我本来也没针对你，是你自己说话阴阳怪气的，如果你在生活中也这么阴阳怪气的，我不多说。

我就是欠打，大哥说的是，大哥教训的好，给你一个赞。
