### ISSUE TITLE
建议作者将这个项目转移到码云上，毕竟是国外网站，下载和访问都很慢

### ISSUE THREAD

**Issue by YongMingMao** [mooseIre/update_miui_ota#47]
re

**Comment by BlackAdlerChi** [comment]
为什么要移到别的地方？GitHub 这么好用。网络问题当然是自己解决。

**Comment by qing666888** [comment]
码云的限制项目文件大小，这么多这么大一个的无法上传。
功能特性 | 社区版 | 企业版
使用场景 | 开源项目 | 个人私有仓库 | 免费版 | 协作开发
总计协作人数 | 不限 | ≦ 5 人 | ≦ 5 人 | 20 ~ 100 人+
仓库总容量 | 5G | 5G | 5G | 20 ~ 100G
单仓库大小 | 1G | 500M | 500M | 1 ~ 3G
单文件大小 | 50M | 50M | 100M | 100 ~ 300M
附件总容量 | 3G | 3G | 3G | 10 ~ 50G +

**Comment by zhangzihanxuejingjing** [comment]
没觉得慢啊。你确定是网站的问题，而不是你网络的问题？

**Comment by liu3734** [comment]
迅雷yyds

**Comment by Beginner-yms** [comment]
笑死，下载是小米官方的链接和作者没关系啊

**Comment by YongMingMao** [comment]
> 笑死，下载是小米官方的链接和作者没关系啊

不知道让你笑死的点在哪里，我的意思是github是国外网站，有一些地方的运营商会不让访问，对一些很少使用github的人来说不太友好而已
