### ISSUE TITLE
提示不能回退到老版本

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [mooseIre/update_miui_ota#48]
大佬，我就是下载的最新的呀
机型：红米k40pro
版本：12.5.4.0
下载包的链接：https://hugeota.d.miui.com/V12.0.5.0.RKKCNXM/miui_HAYDN_V12.0.5.0.RKKCNXM_cdb31bc683_11.0.zip

**Comment by wojiaoxiaomayun** [comment]
包下载错了，k40pro没有提供，我丢

**Comment by aliencaocao** [comment]
你看pr里我提交了k40pro的最新版

**Comment by wojiaoxiaomayun** [comment]
> 你看pr里我提交了k40pro的最新版

哈哈，已更新，那会下午的时候就看见了，我就下载了，谢谢大佬，作者也没抽空合并一波
