### ISSUE TITLE
【建议】增加线刷包链接

### ISSUE THREAD

**Issue by SekiBetu** [mooseIre/update_miui_ota#8]
都是卡刷包啊，有考虑增加线刷包链接吗，可以救机用

**Comment by liyicheneric** [comment]
miui早就只有卡刷包了，除了稳定版还有线刷包，别的版本都只能通过稳定版卡刷

**Comment by SekiBetu** [comment]
https://wdnmd.online/
这边有个红米K30pro的卡刷线刷的链接，可以更新本项目合并一些本项目没有的链接
